### ISSUE TITLE
Linter 

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#271]
- [x] Drop Ruby gem
- [x] Replace with https://www.npmjs.com/package/sass-lint
- [x] Add linter to tests

**Comment by GabrielCousin** [comment]
```
# sass-lint config generated by make-sass-lint-config v0.1.1
#
# The following scss-lint Linters are not yet supported by sass-lint:
# ElsePlacement, PropertyCount, PseudoElement, SelectorDepth
# UnnecessaryParentReference, VendorPrefixes, Compass::*
#
# The following settings/values are unsupported by sass-lint:
# Linter Indentation, option "allow_non_nested_indentation"
# Linter Indentation, option "character"
# Linter PropertySortOrder, option "separate_groups"
# Linter SpaceBeforeBrace, option "allow_single_line_padding"

files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: true
  class-name-format:
    - 0
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 0
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 0
    - max-depth: 3
  no-color-keyword: 1
  no-color-literals: 1
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 1
  no-url-protocols: 0
  placeholder-in-extend: 0
  placeholder-name-format:
    - 0
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - ignore-custom-properties: false
      order:
        - include
        - extend
        - content
        - display
        - visibility
        - flex
        - flex-direction
        - flex-wrap
        - flex-grow
        - flex-shrink
        - position
        - top
        - right
        - bottom
        - left
        - z-index
        - float
        - flex-basis
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - direction
        - align-items
        - align-self
        - justify-content
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - font-family
        - font-size
        - font-weight
        - font-style
        - line-height
        - text-align
        - text-transform
        - text-decoration
        - text-indent
        - letter-spacing
        - text-overflow
        - word-break
        - word-wrap
        - word-spacing
        - white-space
        - vertical-align
        - list-style
        - color
        - background
        - background-color
        - background-image
        - background-position
        - background-repeat
        - background-size
        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-color
        - border-style
        - border-radius
        - box-shadow
        - text-shadow
        - opacity
        - filter
        - '-ms-filter'
        - overflow
        - overflow-x
        - overflow-y
        - cursor
        - pointer-events
        - user-select
        - outline
        - resize
        - transform
        - transform-style
        - transform-origin
        - clip
        - animation
        - animation-name
        - animation-duration
        - animation-ease
        - animation-iteration-count
        - animation-direction
        - backface-visibility
        - transition
        - '-webkit-overflow-scrolling'
        - '-webkit-appearance'
        - box-sizing
        - speak
  quotes:
    - 1
    - style: double
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma: 1
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property:
    - 0
    - properties:
        - color
        - background
        - background-color
  variable-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1
```
