### ISSUE TITLE
.Table--actionnable

### ISSUE THREAD

**Issue by ugogo** [Wisembly/tapestry#47]
Example

``` css
.Table--actionnable {
  .Table-row {
    cursor: pointer;
    transition: background-color .1s ease-out;

    &.selected,
    &.is-selected {
      background-color: $porcelain;
    }
  }
}
```
