### ISSUE TITLE
Create a placeholder for each icon

### ISSUE THREAD

**Issue by ugogo** [Wisembly/tapestry#50]
Genre

``` scss
%icon--poop {
  content: 'abc';
}
```

Comme ça, quand on aura des icônes "dynamiques", on pourra juste faire un

``` scss
.Icon--dynamic {
  @extend %icon--poop
}
```
