### ISSUE TITLE
Table improvements

### ISSUE THREAD

**Issue by ugogo** [Wisembly/tapestry#51]
``` css
.Table--actionnable .Table-row .Table-rowSelector {}
```

should be 

``` css
.Table--actionnable .Table-rowSelector {}
```

---

Do something for sortable tables

``` css
.Table-cell--sortable {
    position: relative;
    cursor: pointer;

    .sortable-label {
      position: relative;
    }

    &.is-active {
      .sortable-label {
        @extend .icon;

        &:before {
          position: absolute;
          right: - $base-fz - 2;
        }
      }

      &[data-sort-direction="asc"] {
        .sortable-label {
          @extend .icon-triangle-up;

          &:before {
            top: 1px;
          }
        }
      }

      &[data-sort-direction="desc"] {
        .sortable-label {
          @extend .icon-triangle-down;

          &:before {
            top: .5px;
          }
        }
      }
    }
  }
```

---
